### ISSUE TITLE
Some punctuation not getting caught by NGram filter

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/ohco2#32]
With "ignorePunctuation" = true, these still get included:
 
· = 0x387
" = 0x22

Obviously, our HMT data will be curated, but for general use…

**Comment by Eumaeus** [comment]
I added those to Corpus.scala. Did "sbt +test", but that failed with:

> sbt.ResolveException: unresolved dependency: com.quantifind#wisp_2.12;0.0.4: not found

If it builds, we could do a minor version bump and re-published whenever.

**Comment by neelsmith** [comment]
Let's stay in close communication before cross simultaneously editing in the same repo.  I think we want to turn around mods fast, so if possible would like to be able to work in and change things in master.  Can I hold on to OHCO2?  

If we're going to generalize, I want to do that right, and look at what Ucode characters are/arenot classified by punctuation property.  Preferable to use that if it suffices.  It doesn't for HMT, but we already catch those issues before data goes into the archive.

**Comment by neelsmith** [comment]
Implemented with the following definition of punctuation:

1. All Unicode Punctuation characters *except* `'` (contraction in English, elision in Greek, prefer to consider part of a word token since word token without that indication could mean something different)
2. Added despicable Greek high dots that in the incoherent spec for Unicode Greek are not identified as part of the Punctuation set

Implemented and tested.
