### ISSUE TITLE
Off by one in ngramHisto

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/ohco2#97]
Reproduce in `sbt console`

Load [million.cex](https://raw.githubusercontent.com/cite-architecture/citedx/master/libraries/million.cex) into a repository.

- Get the textRepository. For this example, that is saved in `val lib`
- Get a copus of Plutarch's Pericles: `val plut = lib.corpus ~~ CtsUrn("urn:cts:greekLit:tlg0007.tlg012:")`
- Ask for 1-grams occurring at least once: `val ng = plut.ngramHisto(1,1,true)`
- There are 903 of them: `ng.size`
- Look at the last one: `ng.histogram(902)`, which is `res20: edu.holycross.shot.ohco2.StringCount = 2 ἡγεμονίαν`

So we're not getting them all.

(In CiteApp, there is an _additional_ off-by-one somewhere that I'm still looking for. Since CiteApp shows the same list of results, but reports 904.)

**Comment by Eumaeus** [comment]
Asking for:

`val ng = plut.ngramHisto(1,0,true)` produces 4117 results and looks like what we want.

**Comment by neelsmith** [comment]
This is correct:  the limiting parameter is NOT "occurring at least N times", but "occurring MORE THAN n times".

For exmple, corpus.ngramHisto("2,0,true) finds ALL occurrences of the bigram since it finds any bigrams that appear more than 0 times.

I'm going to close this for now, and add an issue to check documentation of the ngramHisto function.
